# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#home"
  weight = 10

[[main]]
  name = "Content"
  url = "#content"
  weight = 30

[[main]]
  name = "Hands on"
  url = "#hands-on"
  weight = 40

[[main]]
  name = "Bibliography"
  url = "#bibliography"
  weight = 50

